#!/bin/bash

version="ooRexx sandbox-jlf"
echo Setting environment for running $version

# add to front of path
prepend_path()
{
  if eval test -z "\"\$$1\"" || ! eval test -z "\"\${$1##*:$2:*}\"" -o -z "\"\${$1%%*:$2}\"" -o -z "\"\${$1##$2:*}\"" -o -z "\"\${$1##$2}\"" ; then
    eval "$1=\"$2\":\$$1"
  fi
}

me=$(readlink -f ${BASH_SOURCE[0]})
export OOREXX_HOME=`dirname "$me"`

echo -n -e "\033]0;$version\007"

export PATH
export LD_LIBRARY_PATH
export NLSPATH
export CPLUS_INCLUDE_PATH
export LIBRARY_PATH

prepend_path PATH $OOREXX_HOME/bin
prepend_path PATH $OOREXX_HOME/packages
prepend_path LD_LIBRARY_PATH $OOREXX_HOME/lib
prepend_path NLSPATH $OOREXX_HOME/bin/rexx.cat
prepend_path CPLUS_INCLUDE_PATH $OOREXX_HOME/include
prepend_path LIBRARY_PATH $OOREXX_HOME/lib

source $OOREXX_HOME/bsf4oorexx/install/setEnvironment4BSF.sh
