

/*----------------------------------------------------------------------------*/
/*                                                                            */
/* Copyright (c) 1995, 2004 IBM Corporation. All rights reserved.             */
/* Copyright (c) 2005-2009 Rexx Language Association. All rights reserved.    */
/*                                                                            */
/* This program and the accompanying materials are made available under       */
/* the terms of the Common Public License v1.0 which accompanies this         */
/* distribution. A copy is also available at the following address:           */
/* http://www.ibm.com/developerworks/oss/CPLv1.0.htm                          */
/*                                                                            */
/* Redistribution and use in source and binary forms, with or                 */
/* without modification, are permitted provided that the following            */
/* conditions are met:                                                        */
/*                                                                            */
/* Redistributions of source code must retain the above copyright             */
/* notice, this list of conditions and the following disclaimer.              */
/* Redistributions in binary form must reproduce the above copyright          */
/* notice, this list of conditions and the following disclaimer in            */
/* the documentation and/or other materials provided with the distribution.   */
/*                                                                            */
/* Neither the name of Rexx Language Association nor the names                */
/* of its contributors may be used to endorse or promote products             */
/* derived from this software without specific prior written permission.      */
/*                                                                            */
/* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS        */
/* "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT          */
/* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS          */
/* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT   */
/* OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,      */
/* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED   */
/* TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,        */
/* OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY     */
/* OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING    */
/* NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS         */
/* SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.               */
/*                                                                            */
/*----------------------------------------------------------------------------*/
/******************************************************************************/
/* REXX  Support                                                              */
/*                                                                            */
/* Rexx primitive class id codes                                              */
/*                                                                            */
/*        -- DO NOT CHANGE THIS FILE, ALL CHANGES WILL BE LOST! --            */
/*                  -- FILE WAS GENERATED BY ClassTypeIds.xsl --              */
/******************************************************************************/

#ifndef ClassTypeCodes_Included
#define ClassTypeCodes_Included

typedef enum
{
    T_First_Primitive_Class = 0,
    T_First_Exported_Class = 0,

    T_Object = 0,
    T_ObjectClass = 1,
    T_Class = 2,
    T_ClassClass = 3,
    T_Array = 4,
    T_ArrayClass = 5,
    T_Directory = 6,
    T_DirectoryClass = 7,
    T_Integer = 8,
    T_IntegerClass = 9,
    T_List = 10,
    T_ListClass = 11,
    T_Message = 12,
    T_MessageClass = 13,
    T_Method = 14,
    T_MethodClass = 15,
    T_NumberString = 16,
    T_NumberStringClass = 17,
    T_Queue = 18,
    T_QueueClass = 19,
    T_Stem = 20,
    T_StemClass = 21,
    T_String = 22,
    T_StringClass = 23,
    T_Supplier = 24,
    T_SupplierClass = 25,
    T_Table = 26,
    T_TableClass = 27,
    T_Relation = 28,
    T_RelationClass = 29,
    T_MutableBuffer = 30,
    T_MutableBufferClass = 31,
    T_Pointer = 32,
    T_PointerClass = 33,
    T_Buffer = 34,
    T_BufferClass = 35,
    T_WeakReference = 36,
    T_WeakReferenceClass = 37,
    T_Routine = 38,
    T_RoutineClass = 39,
    T_Package = 40,
    T_PackageClass = 41,
    T_RexxContext = 42,
    T_RexxContextClass = 43,
    T_IdentityTable = 44,
    T_IdentityTableClass = 45,
    T_StackFrame = 46,
    T_StackFrameClass = 47,
    T_RexxBlock = 48,
    T_RexxBlockClass = 49,
    T_RexxText = 50,
    T_RexxTextClass = 51,
    T_Unicode = 52,
    T_UnicodeClass = 53,

    T_Last_Exported_Class = 53,
    
    T_First_Internal_Class = 54,

    T_NilObject = 54,
    T_Behaviour = 55,
    T_RexxSource = 56,
    T_LibraryPackage = 57,
    T_RexxCode = 58,
    T_NativeMethod = 59,
    T_NativeRoutine = 60,
    T_RegisteredRoutine = 61,
    T_CPPCode = 62,
    T_AttributeGetterCode = 63,
    T_AttributeSetterCode = 64,
    T_ConstantGetterCode = 65,
    T_AbstractCode = 66,
    T_HashTable = 67,
    T_ListTable = 68,
    T_SmartBuffer = 69,
    T_Variable = 70,
    T_VariableDictionary = 71,
    T_VariableTerm = 72,
    T_CompoundVariableTerm = 73,
    T_StemVariableTerm = 74,
    T_DotVariableTerm = 75,
    T_IndirectVariableTerm = 76,
    T_FunctionCallTerm = 77,
    T_MessageSendTerm = 78,
    T_UnaryOperatorTerm = 79,
    T_BinaryOperatorTerm = 80,
    T_LogicalTerm = 81,
    T_ListTerm = 82,
    T_Instruction = 83,
    T_AddressInstruction = 84,
    T_AssignmentInstruction = 85,
    T_CallInstruction = 86,
    T_CommandInstruction = 87,
    T_DoInstruction = 88,
    T_DropInstruction = 89,
    T_ElseInstruction = 90,
    T_EndInstruction = 91,
    T_EndIfInstruction = 92,
    T_ExitInstruction = 93,
    T_ExposeInstruction = 94,
    T_ForwardInstruction = 95,
    T_GuardInstruction = 96,
    T_IfInstruction = 97,
    T_InterpretInstruction = 98,
    T_LabelInstruction = 99,
    T_LeaveInstruction = 100,
    T_MessageInstruction = 101,
    T_NopInstruction = 102,
    T_NumericInstruction = 103,
    T_OptionsInstruction = 104,
    T_OtherwiseInstruction = 105,
    T_ParseInstruction = 106,
    T_ProcedureInstruction = 107,
    T_QueueInstruction = 108,
    T_RaiseInstruction = 109,
    T_ReplyInstruction = 110,
    T_ReturnInstruction = 111,
    T_SayInstruction = 112,
    T_SelectInstruction = 113,
    T_SignalInstruction = 114,
    T_ThenInstruction = 115,
    T_TraceInstruction = 116,
    T_UpperInstruction = 117,
    T_UseInstruction = 118,
    T_ClassDirective = 119,
    T_ExtensionDirective = 120,
    T_LibraryDirective = 121,
    T_RequiresDirective = 122,
    T_CompoundElement = 123,
    T_ParseTrigger = 124,
    T_SourceLiteral = 125,

    T_Last_Internal_Class = 125,
    
    T_First_Transient_Class = 126,

    T_Memory = 126,
    T_InternalStack = 127,
    T_Stack = 128,
    T_Activity = 129,
    T_Activation = 130,
    T_NativeActivation = 131,
    T_ActivationFrameBuffer = 132,
    T_Envelope = 133,
    T_Clause = 134,
    T_Token = 135,
    T_DoBlock = 136,
    T_InterpreterInstance = 137,
    T_SecurityManager = 138,
    T_CommandHandler = 139,

    T_Last_Transient_Class = 139,
    T_Last_Primitive_Class = 139,
    T_Last_Class_Type = 139,
    
} ClassTypeCode;

/* -------------------------------------------------------------------------- */
/* --            ==================================================        -- */
/* --            DO NOT CHANGE THIS FILE, ALL CHANGES WILL BE LOST!        -- */
/* --            ==================================================        -- */
/* -------------------------------------------------------------------------- */
#endif

